version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: apiadmin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-front
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    
 #Nginx Service
  # nginx:
  #   image: nginx:alpine
  #   container_name: front-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d:/etc/nginx/conf.d/
  #   networks:
  #     - mynetwork

   #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  
networks:
   app-network:
    driver: bridge