version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: apiadmin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-front
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    
   #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx-front
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

  
networks:
   app-network:
    driver: bridge